// Every tunable number in the simulation. Tune here, nowhere else.
export const B = {
  runWeeks: 1040, anniversaryWeek: 1040, retireFromWeek: 520, startBrand: 5, runwayLoseWeeks: 8, maxHistory: 800,
  salary: { junior: 900, mid: 1600, senior: 2600 }, hireFeeWeeks: 2,
  candidateRefreshWeeks: 4, candidateCount: 5,
  // Level-ups in one week that earn a team growth line in #wins.
  growthDigestMin: 3,
  xpPerLevel: 60, xpPerWeekWorking: 8, promoteMidLevel: 5, promoteSeniorLevel: 10, maxLevel: 20,
  juniorXpAutomationPenalty: 0.7, mentorXpMult: 2.2, mentorOutputMult: 0.6,
  basePoints: 4, pointsPerLevel: 1.1,
  roleWeights: {
    engineer: { features: 0.45, reliability: 0.35, novelty: 0.1, polish: 0.1 },
    designer: { features: 0.2, reliability: 0, novelty: 0.3, polish: 0.5 },
    marketer: { features: 0, reliability: 0, novelty: 0.3, polish: 0.1 },
    security: { features: 0, reliability: 0.4, novelty: 0, polish: 0 },
    support: { features: 0.05, reliability: 0.1, novelty: 0, polish: 0.1 },
    sales: { features: 0.05, reliability: 0, novelty: 0.05, polish: 0 },
  },
  seniorityOutput: { junior: 0.6, mid: 1.0, senior: 1.45 },
  hardProblemNovelty: 6, craftFridaysOutput: 0.9, comprehensionReviewSpeed: 0.85,
  autoEngPoints: 45, autoEngWeights: { features: 0.55, reliability: 0.25, novelty: 0.05, polish: 0.15 },
  autoOpsMaintenance: 60, autoQaReliability: 0.3,
  pairAutoMult: 0.6, pairMeaningDrainMult: 0.3,
  oversightHoursPerLevel: { engineering: 20, support: 14, sales: 8, marketing: 6, qa: 10, ops: 24 },
  oversightHoursPerPerson: 20,
  supportHoursPerCustomer: 1 / 150, supportHoursPerPerson: 40, autoSupportHours: 400,
  salesCloseBoostPerPerson: 0.006, autoSalesBoost: 0.008,
  meaningDrain: { junior: 0.6, mid: 1.1, senior: 1.8 }, meaningBaseRecovery: 0.35,
  meaningRecovery: { mentor: 1.2, mentee: 0.6, hardProblem: 1.6, craft: 1.1, sabbatical: 4, oversight: 0.4, craftFridays: 0.5, owner: 0.4 },
  meaningGrind: 0.22, meaningGrindPerHead: 0.02, meaningCeilingBand: 50,
  yearlyRaise: 0.04, modelCostMult: 2, autoCostMult: 0.6, overheadFreeHeadcount: 12, overheadPerHead: 300, staleChurn: 0.012,
  meaningCatchBonus: 12, meaningAwardBonus: 8, meaningLaunchBonus: 4,
  coastingBelow: 35, burnoutBelow: 15, coastingOutput: 0.6, burnoutOutput: 0.2,
  resignChance: { coasting: 0.01, burnout: 0.07 }, burnoutWeeksBeforeResign: 3, sabbaticalWeeks: 4,
  staminaDrainWorking: 0.6, staminaRecovery: 1.2, staminaLowBelow: 25,
  knowledgeGainWorking: 0.5, knowledgeGainMentee: 1.0, newHireKnowledge: 10,
  ikBaseline: 1.35, ikPerProduct: 0.68,
  debtFromEngAuto: 0.8, debtFromQaAuto: 0.35, debtFromOpsAuto: 0.3, debtPerProduct: 0.04,
  debtPaydownPerSeniorEng: 0.35, debtPaydownReviews: 0.9, debtPaydownRefactor: 15,
  debtFromDeparturePerKnowledge: 0.12, debtLowIkThreshold: 40, debtLowIkRate: 0.03,
  sizes: {
    small: { points: 400, cost: 2000, minStage: 0 },
    medium: { points: 1000, cost: 8000, minStage: 0 },
    large: { points: 2400, cost: 25000, minStage: 1 },
  },
  pointsGrowthPerYear: 0.1, expectationGrowth: 0.1, expectationYearsCap: 5, reviewNoise: 0.9, balancePenaltyBelow: 0.08,
  qualityBase: 0.5, autoQualityBase: 0.3, autoQualityPerCap: 0.6, autoAssistQuality: 0.9,
  reviewBase: 6.1, reviewScale: 4.1, fitScoreScale: 3.3, reviewsReliabilityBonus: 0.1, updateOldScoreWeight: 0.4,
  migrationPoints: 250, updatePointsMult: 0.3, refactorPoints: 450, craftPoints: 320,
  appealExp: 1.5, noveltyAppealPer: 1 / 6, appealScale: 5, sizeAppeal: { small: 1, medium: 1.4, large: 2 }, incumbentStrengthGrowth: 0.03, cloneStrength: 60,
  marketScale: 0.15, adoptionStart: 0.4, adoptionPerYear: 0.06, incumbentErosion: 0.002, erosionScore: 8, candidateSkillPerYear: 2.5,
  acquisitionRate: 0.04, hypeAcquisition: 0.0012,
  baseChurn: 0.008, minChurn: 0.002, churnBrandRelief: 0.00004, wrapperChurn: 0.02, supportShortfallChurn: 0.02, outageChurn: 0.05,
  maintenancePerProduct: 3, maintenancePerCustomer: 1 / 4000, healthDecay: 6, healthRecovery: 1, uptimeFloor: 0.5,
  noveltyDecay: 0.08, enterpriseComplianceMult: 0.75,
  hypeDecay: 0.08, brandDecay: 0.03, brandDecayRate: 0.012, marketerHypePerWeek: 1.2, autoMarketingHype: 0.4,
  autoMarketingBrandPenalty: 0.6, wrapperGap: 2.5, wrapperBrandHit: 4,
  showHnEveryWeeks: 6, cloneChanceBase: 0.012, cloneChanceYearGrowth: 0.35, cloneDecay: 0.01,
  copyDelayWeeks: [26, 52], copyNoveltyMult: 0.5, copyIncumbentMult: 1.08,
  vendorReleaseEveryWeeks: 26, vendorCapabilityStep: 7, deprecateChance: 0.5, priceHikeChance: 0.08,
  migrationDeadlineWeeks: 26, missedMigrationHealth: 3, priceHikeMult: 1.3,
  rogueBase: 0.015, rogueShortfallFloor: 0.08, catchBase: 0.75, catchMax: 0.95, caughtDamageMult: 0.2,
  ransomFloor: 10000, ransomCap: 400000, ransomCashShare: 0.2, ransomMrrMonths: 0.5, ransomMaxCashShare: 0.6,
  cyberGraceWeeks: 26, cyberBase: 0.006, cyberPerMrr: 0.00000004, cyberMax: 0.12,
  incidentCashPerSeverity: 4000, incidentCashYearGrowth: 0.3, outageMinSeverity: 3,
  postureSecurityPerSkill: 3.2, postureAudit: 20, postureAuditDecay: 0.4, postureTooling: 12, postureDebtPenalty: 0.5,
  auditCost: 15000, toolingWeekly: 900, consultantCost: 45000, founderFixMult: 1.5, bridgeOfferCooldownWeeks: 26,
  outageComplexityPerProduct: 0.2, fixersCounted: 3, outageCollapseWeeks: 6, collapseMrrShare: 0.5, collapseIkBelow: 20,
  gpuWeeklySelfHost: 1200, randomEventChance: 0.22,
  standupDailyOutput: -0.03, standupDailyMeaning: 0.3, standupIkBonus: 0.1,
  // Emoji reactions by a post's weight: routine chatter and replies rarely get any (one or two when they do),
  // and a trivial post now and then gets a pile of one emoji as a joke. Big posts use reactionMax.
  reactions: { routineChance: 0.3, routineSecond: 0.25, replyChance: 0.12, pileOnChance: 0.012, pileOnMin: 6, pileOnMax: 10 },
  chatLogSize: 80, eventGraceWeeks: 10, decisionGapWeeks: 3, reactionMax: 6, chatMemory: 24,
  saySituationChance: 0.8, sayExchangeChance: 0.22, saySoloChance: 0.45, asyncStandupPostChance: 0.35, standupMemory: 80, helloMemory: 8, standupPersonMemory: 16, ongoingSituationChance: 0.2, chatSituationChance: 0.7, threadChance: 0.15, chatSoloChance: 0.3,
  rareExchangeShare: 0.34, atChannelChance: 0.03, atChannelWarrantedChance: 0.3, atChannelSighChance: 0.4, atChannelGapWeeks: 40, runningJokesPerRun: 3, jokeGapWeeks: [8, 20], talkMemory: 60, exchangeCooldownWeeks: 52, neighbourTiles: 3,
  funding: {
    bootstrapped: { cash: 110000, scoreMult: 1, brand: 0, seniorCandidates: 0 },
    family: { cash: 150000, scoreMult: 0.97, brand: 0, seniorCandidates: 0 },
    preseed: { cash: 300000, scoreMult: 0.96, brand: 8, seniorCandidates: 2 },
  },
  founderStrengthBonus: 3, founderIkWeight: 0.4, founderGeneralistWeights: { features: 0.3, polish: 0.15, reliability: 0.2, novelty: 0.1 },
  botBuildersPerProject: 6, botTimeOffStrain: 70, botCancelUnstaffedWeeks: 2, botExpandCushion: 2, botDialCash: 3000000, botAcquireCushion: 4, botAcquireDesks: 3, botMoonshotCushion: 3, botFameBelow: 30, botFameCushion: 6,
  eraAutoEngMult: { classic: 1, chatgbt: 1, agents: 3, consolidation: 3, plateau: 2 },
  unlockGapWeeks: 6,
  lockdownWeek: 62, lockdownWeeks: 10, hybridRemoteShare: 0.4, remoteFirstShare: 0.65, remoteLearningMult: 0.6,
  remoteRentMult: 0.75, remoteExtraCandidates: 1, remoteMeaningGrind: 0.12, remotePatternWeeks: [8, 13],
  callWeekChance: 0.2, callMutedChance: 0.25, callFrozenChance: 0.1, callBadCameraChance: 0.12, callMomentChance: 0.6,
  remoteKnowledgeMult: 0.8, remoteNoveltyMult: 0.7, remoteFixPenalty: 0.3,
  rivalFromWeek: 104, rivalStartStrength: 20, rivalGrowth: 0.3, rivalStallChance: 0.004, rivalFateAfterWeeks: 30,
  rivalStrengthScale: 3, rivalMergeCustomers: 0.25, petMeaningRecovery: 0.04, petMaxCount: 2,
  strainTiredBelow: 35, strainFromTired: 3, strainUnderstaffed: 2, strainPerCrunch: 25, strainOnCall: 3, strainOnCallWeeks: 8, strainSlack: 1, strainSlackMax: 3,
  strainRecoverWorking: 1.5, strainRestedAbove: 60, strainRecoverRest: 5, strainRecoverAway: 20, noCrunchStrainMult: 0.5, noCrunchOutput: -0.03,
  crunchOutput: 0.15, crunchStrain: 1.5, crunchMeaningDrain: 0.3,
  strainWarn: 60, strainBurnout: 85, strainRecoveredBelow: 55, strainOutputPenalty: 0.3, timeOffWeeks: 2,
  vacationWeeks: 2, vacationFirstAfter: 20, vacationMaxShare: 0.15, vacationPostponeWeeks: 4, vacationMaxPostpones: 2,
  vacationPostponeStrain: 6, vacationStamina: 60,
  incentiveEveryWeeks: 8, musicNightDancers: [3, 5], waffleLaunches: 20, waffleLevel: 20, waffleCooldownWeeks: 156, incentiveWinnerMeaning: 6, incentiveEnvy: 1, incentiveOutput: 0.06, incentiveFatigue: 0.01,
  awardAiScore: 8.5, awardWorkplaceStaff: 10, awardWorkplaceMeaning: 78, awardWorkplaceStreak: 2, awardTrustedIncidents: 0, awardAiHype: 15, awardWorkplacePride: 1, awardTrustedBrand: 2,
  recordEngPointsPerFeature: 8, recordDesignPointsPerFeature: 120, recordPointsPerPr: 30, recordTicketHours: 2, recordCustomersPerDeal: 25,
  hqDeskCap: 30, expansionDeskStep: 5, topPayAttrition: 0.6, upkeepAttrition: 0.85, upkeepMeaningRecovery: 0.15,
  agentSpendFloor: 3000, agentAuditWeeks: 8, agentInvoiceWeeks: 20, agentAuditRogueRelief: 0.3, agentCapLevel: 0.5,
  rivalMergeBase: 150000, rivalMergePerStrength: 60000,
  beatAgentBillAfter: 45, beatMegaroundAfter: 95, beatFloorNextDoorAfter: 130, megaroundWeeks: 26,
  productNameMax: 20,
  // Yak reply prompts: at most chatPromptsOpen open, a new one at least chatPromptGapWeeks after the last,
  // each open for chatPromptExpiryWeeks, and answered ones kept chatPromptsKept weeks for the thread view.
  // The founders' quick posts in Yak: a shared cooldown, a repeat window that makes the same post fall flat,
  // and the small effects of each post when it lands or backfires.
  postsEnabled: true,
  posts: {
    cooldownWeeks: 2, repeatWeeks: 8, newsWeeks: 2, replyWeeks: 2, lowMorale: 30, pizzaPerHead: 25,
    pepTalk: 2, meme: 2, pizza: 3, pizzaStamina: 10, news: 3, backfire: 1, scare: 2, memeBackfire: 3, blame: 1, fixHealth: 3,
  },
  chatPromptsEnabled: true, chatPromptsOpen: 1, chatPromptGapWeeks: 1, chatPromptExpiryWeeks: 3, chatPromptsKept: 4, chatPromptChance: 0.6, chatPromptFromWeek: 6,
  prompts: {
    strainAt: 40, lateWeeks: 12, newHireWeeks: 3, supportShortfall: 0.2, lateProgress: 0.6, agentLevel: 0.3,
    restStrain: 20, pushStrain: 3, pushOutput: 0.02, launchHype: 4, cakeCost: 300, subtweetBackfire: 0.25,
    crunchOutput: 0.04, reviewDebt: 3, mergeDebt: 4, lunchCost: 40, teamLunchCost: 400,
  },
  // The office classics: banner, cover sheets, stapler, consultants, printer and the Saturday ask.
  nods: {
    bannerStaff: 12, bannerOutput: 0.02, bannerDrain: 0.05, bannerWeeks: 26, bannerStays: 104, bannerIronyMiss: 0.2, bannerReturnFee: 300,
    coverStaff: 8, coverOutput: -0.02, coverWeeks: 26, coverIk: 3,
    staplerTenureWeeks: 104, staplerLoss: 25, staplerBack: 10, staplerBackWeeks: 13, staplerKeep: 5, staplerSaving: 200,
    consultantStaff: 15, consultantFee: 60000, consultantCuts: 2, consultantNewHireWeeks: 13, consultantMinEligible: 3,
    consultantOutput: 0.05, consultantWeeks: 26, consultantMeaning: -4, layoffGapWeeks: 52,
    printerCost: 2500, printerMeaning: 6, printerWreckWeeks: 4, printerRepair: 300, printLessOutput: -0.01, printLessWeeks: 13,
    saturdayStaff: 10, saturdayOutput: 0.08, saturdayWeeks: 2, saturdayStrain: 10, saturdayMeaning: -3, saturdayNoTeam: 2, saturdayNoSubject: -3,
  },
  // Staff names: the share of draws from the international tier, the share of the US mix that is South
  // Asian, and how often a last name comes from the same tier as the first name.
  intlNameShare: 0.28, southAsianNameShare: 0.18, nameTierMatch: 0.7,
  fameDecay: 0.3, fameChurnRelief: 0.25, fameHireRelief: 0.4,
  moonshotAfterConsolidation: 100, moonshotRevenueShare: 0.25, moonshotMinWeekly: 50000, moonshotCheckinWeeks: 26, moonshotCheckins: 4,
  moonshotProduct: { stats: { features: 200, polish: 180, reliability: 160, novelty: 120 }, score: 8.6, hype: 60, novelty: 10, health: 90 },
  moonshotMinMrr: 20000, foundationPurpose: { people: 8, trust: 5 },
  moonshotSuccess: 0.5, moonshotCustomers: 0.15, moonshotStopFame: 3, moonshotFailFame: 8, moonshotFailBrand: 2, moonshotWinFame: 20, moonshotWinBrand: 8,
  lastBetWeek: 900, lastBetCashShare: 0.3, lastBetSuccess: 0.45, lastBetWinFame: 30, lastBetLoseFame: 10, lastBetWinBrand: 10, lastBetLoseBrand: 5,
  foundationCashShare: 0.25, foundationFame: 15, foundationMeaning: 5, keysSeniorMeaning: 8,
  officePropsMax: 6,
  forSaleWeek: 30, forSaleWeeks: 13, forSalePerRound: 3, forSaleMinArr: 600000, forSaleArrShare: [0.03, 0.12],
  forSalePriceMult: [6, 10], forSaleConsolidationDiscount: 0.8, acquiredScore: [6, 7.8], acquiredBrand: 1,
  epilogueOutcomeLines: 2, epilogueLines: 7,
  alumniKept: 40, aiSummitWeek: 20, summitCost: { small: 20000, big: 80000 }, summitEraMult: [1, 1, 1.5, 2, 2.5], summitPauseAfter: 2,
  moveOnPerYear: 0.025, moveOnTenureWeeks: 156, moveOnMinStaff: 5,
  attritionPerYear: 0.025, attritionAfterWeeks: 26, attritionMinStaff: 5, attritionMeaningBelow: 60, attritionMeaningSpan: 20,
  attritionUnhappy: 2, attritionUnderpaidBelow: 0.95, attritionUnderpaid: 1.8, attritionRival: 1.4, attritionPerkRelief: 1.5,
  attritionPerkFloor: 0.35, attritionGoodPolicy: 0.8, referralMeaning: 70, candidateListMax: 8, hearingFromWeek: 416,
  purposeStart: { craft: 55, people: 55, trust: 55, growth: 40 }, missionAfterWeeks: 8, purposeTestsKept: 12,
  purposeMeaning: 0.3, purposeRetention: 0.4, purposeAppeal: 0.3, purposeHiring: 6,
  plateauPolishAppeal: 1.5, plateauBrandAppeal: 0.5,
  eraJitterWeeks: 13, chatgbtAutomationCap: 0.5, chatgbtAutomationFns: ['support', 'marketing'], noModelTrust: 0.85,
  eraCompetition: { classic: 1, chatgbt: 1.12, agents: 1.25, consolidation: 1.4, plateau: 1.45 }, consolidationVendorEveryWeeks: 13, consolidationDeprecateChance: 0.8,
  // How often an acquisition offer comes up among random events: the main dial for how often good play exits.
  acquisitionOfferWeight: 4.5, acquisitionOfferOpenWeeks: 26, consolidationOfferMult: 0.95,
  ipoMrr: 2850000, ipoBrand: 60, acquisitionOfferMrr: 2550000, acquisitionOfferBrand: 50, leaderCategoriesToWin: 3,
};
