// The trailer's script and timing table, from scripts/trailer/config.js: every narration line's beat,
// start, window and room before the cut, and with --vo the rendered files' measured speech and fit.
//
//   node scripts/trailer/vo/table.mjs [--vo <dir>] [--write]
//
// Window rules, all in seconds:
//   - the first line in a beat starts 0.2 to 0.5 after the beat's cut;
//   - a window (offset plus max) closes at least 0.3 before the next cut; the last beat only has to hold it;
//   - with --vo, each file's speech fits its max, ends at least 0.3 before the cut, and leaves at least 0.4
//     before the next line in the same beat starts.
// --write renders the windows (never the measured files) to docs/trailer/script.md, which is generated:
// edit config.js and rerun.
// Exits 1 when any rule fails.
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BEATS, VO } from '../config.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const argv = process.argv.slice(2);
const voDir = argv.includes('--vo') ? argv[argv.indexOf('--vo') + 1] : null;
const RULE = { startMin: 0.2, startMax: 0.5, beforeCut: 0.3, between: 0.4 };
const SR = 48000;

const beats = [];
let t = 0;
for (const b of BEATS) { beats.push({ id: b.id, start: t, dur: b.dur }); t += b.dur; }
const total = t;
const beatOf = Object.fromEntries(beats.map((b, i) => [b.id, { ...b, last: i === beats.length - 1 }]));

// Speech bounds of a rendered line: first and last sample within 45 dB of its peak.
function speech(file) {
  const pcm = execFileSync('ffmpeg', ['-v', 'error', '-i', file, '-ac', '1', '-ar', String(SR), '-f', 'f32le', '-'], { maxBuffer: 1 << 28 });
  const y = new Float32Array(pcm.buffer, pcm.byteOffset, pcm.length / 4);
  let peak = 0;
  for (const v of y) peak = Math.max(peak, Math.abs(v));
  const floor = peak * 10 ** (-45 / 20);
  let a = 0, b = y.length - 1;
  while (a < y.length && Math.abs(y[a]) <= floor) a++;
  while (b > a && Math.abs(y[b]) <= floor) b--;
  return { lead: a / SR, length: (b - a) / SR };
}

const f2 = (x) => (x == null ? '' : x.toFixed(2));
const problems = [];
const rows = VO.lines.map((l, i) => {
  const beat = beatOf[l.at.beat];
  if (!beat) { problems.push(`${l.id}: unknown beat ${l.at.beat}`); return null; }
  const offset = l.at.offset ?? 0;
  const firstInBeat = !VO.lines.slice(0, i).some((p) => p.at.beat === l.at.beat);
  const room = beat.dur - (offset + l.max);
  const need = beat.last ? 0 : RULE.beforeCut;
  const issues = [];
  if (l.max == null) issues.push('no max');
  if (firstInBeat && (offset < RULE.startMin || offset > RULE.startMax)) issues.push(`starts ${f2(offset)} after the cut`);
  if (room < need - 1e-9) issues.push(`window closes ${f2(room)} before the cut`);
  const row = { id: l.id, beat: beat.id, beatStart: beat.start, beatDur: beat.dur, start: beat.start + offset, offset, max: l.max, room, text: l.text, issues };
  if (voDir) {
    const file = join(voDir, `${l.id}.wav`);
    if (!existsSync(file)) issues.push('no file');
    else {
      const s = speech(file);
      row.speech = s.length;
      row.lead = s.lead;
      row.speechEnd = offset + s.lead + s.length;
      if (s.length > l.max + 1e-9) issues.push(`speech ${f2(s.length)} over max`);
      if (beat.dur - row.speechEnd < need - 1e-9) issues.push(`speech ends ${f2(beat.dur - row.speechEnd)} before the cut`);
    }
  }
  return row;
}).filter(Boolean);
if (voDir) {
  for (const [i, r] of rows.entries()) {
    const next = rows[i + 1];
    if (next && next.beat === r.beat && r.speechEnd != null && next.offset - r.speechEnd < RULE.between - 1e-9) {
      r.issues.push(`${f2(next.offset - r.speechEnd)} before ${next.id}`);
    }
  }
}
for (const r of rows) for (const p of r.issues) problems.push(`${r.id}: ${p}`);

const head = ['Line', 'Beat', 'Beat start', 'Beat length', 'Starts at', 'Offset', 'Max', 'Room before cut'];
if (voDir) head.push('Speech', 'Lead-in', 'Fit');
head.push('Text');
const body = rows.map((r) => {
  const cells = [r.id, r.beat, f2(r.beatStart), f2(r.beatDur), f2(r.start), f2(r.offset), f2(r.max), f2(r.room)];
  if (voDir) cells.push(f2(r.speech), f2(r.lead), r.issues.length ? r.issues.join('; ') : 'fits');
  else if (r.issues.length) cells[7] += ` (${r.issues.join('; ')})`;
  cells.push(r.text.replace(/\|/g, '\\|'));
  return `| ${cells.join(' | ')} |`;
});
const table = [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...body].join('\n');

if (argv.includes('--write')) {
  if (voDir) { process.stderr.write('trailer-vo: --write renders the windows only; run it without --vo\n'); process.exit(2); }
  const doc = `# Trailer script and timing\n\nGenerated by \`node scripts/trailer/vo/table.mjs --write\` from \`scripts/trailer/config.js\`; edit the config and rerun, never this file. Times are seconds; the trailer runs ${f2(total)}. "Room before cut" is how much of the beat is left after the line's window closes.\n\n${table}\n`;
  writeFileSync(join(ROOT, 'docs/trailer/script.md'), doc);
}
process.stdout.write(`${table}\n\ntrailer: ${f2(total)} s, ${rows.length} lines${voDir ? `, files from ${voDir}` : ''}\n`);
if (problems.length) {
  process.stderr.write(`trailer-vo: ${problems.length} problem(s)\n${problems.map((p) => `  ${p}`).join('\n')}\n`);
  process.exit(1);
}
