import { readFileSync, writeFileSync } from 'node:fs';
const load = n => JSON.parse(readFileSync(`shots/chatter/${n}.json`));
const before=load('before'), after=load('after'), names={garage:'Garage',floor:'Office Floor',hq:'HQ'};
const need=t=>Math.max(2.5,t.trim().split(/\s+/).length*.25);
const fmt=n=>Number(n.toFixed(2));
const pair=(a,b)=>`${fmt(a)} / ${fmt(b)}`;
const finished=x=>x.bubbles.filter(b=>b.done);
const misses=x=>finished(x).filter(b=>(b.visible??0)+.05<need(b.text)).length;
let out='Before / after. Rates are per real-time minute.\n\n| Office | Speed | Speech/min | Yak/min | Max bubbles | Bubbles below reading minimum |\n|---|---:|---:|---:|---:|---:|\n';
for(let i=0;i<before.length;i++){let a=before[i],b=after[i];out+=`| ${names[a.stage]} | ${a.speed}x | ${pair(a.bubbles.length/2,b.bubbles.length/2)} | ${pair(a.yak.length/2,b.yak.length/2)} | ${a.stats.max} / ${b.stats.max} | ${misses(a)}/${finished(a).length} / ${misses(b)}/${finished(b).length} |\n`;}
out+='\nTwo-minute windows in the actual browser game loop, 30 fps, seeded renderer (12345), Medium quality at 1280x800. The balanced bot supplies actions once per week and checks decisions every four seconds; tutorial cards are dismissed. Both builds use the same seed-1 saves: Garage week 12 (2 staff), Office Floor week 116 (6 staff), HQ week 262 (20 staff). The bot continues playing, including hires and policy choices. Rates divide by the full 120 seconds, including decision and spotlight holds. These are three sampled windows, not a full-career guarantee.\n';
const snaps=load('snapshots');out=out.replace('HQ week 262 (20 staff)',`HQ week ${snaps.hq.week} (${snaps.hq.staff} staff)`);out=out.replace('Office Floor week 116 (6 staff)',`Office Floor week ${snaps.floor.week} (${snaps.floor.staff} staff)`);
out+='\n<details><summary>Reading time and overlap</summary>\n\nA bubble counts as visible when its DOM box is present and its opacity exceeds 0.5. Dwell sums those frames; a reading failure is below max(2.5 seconds, 0.25 seconds per word), with 0.05 seconds of sampling tolerance. Lines still visible at the end are excluded from dwell failures. Yak dwell measures new posts actually visible in the open #general viewport; hidden channels are included in arrival rates but excluded from dwell. A Yak row is visible when at least 40 pixels of its height, or its whole height if shorter, clears the scrolling container.\n\n| Office / speed | Min bubble dwell, s | Seconds with 2+ bubbles | Seconds with bubble box overlap | Yak short / completed visible | Max visible new Yak rows |\n|---|---:|---:|---:|---:|---:|\n';
for(let i=0;i<before.length;i++){const a=before[i],b=after[i];const ys=x=>x.yak.filter(y=>y.visible>0&&!y.lastVisible);const yshort=x=>ys(x).filter(y=>y.visible+.05<need(y.e.text)).length;out+=`| ${names[a.stage]} ${a.speed}x | ${pair(Math.min(...finished(a).map(x=>x.visible??0)),Math.min(...finished(b).map(x=>x.visible??0)))} | ${pair(a.stats.overlapFrames/30,b.stats.overlapFrames/30)} | ${pair(a.stats.pairFrames/30,b.stats.pairFrames/30)} | ${yshort(a)}/${ys(a).length} / ${yshort(b)}/${ys(b).length} | ${a.stats.yakMax} / ${b.stats.yakMax} |\n`;}
out+='\nYak keeps multiple rows available for rereading. Speech overlap counts simultaneous boxes and geometrically intersecting boxes separately. Both are zero in every after window. Spotlight moments can exceed the ordinary one-bubble limit by design.\n\n</details>\n';
function bubbleSource(x,b){const o=x.origins.find(([,v])=>v.event.type==='say'&&v.event.text===b.text)?.[1];if(o){if(o.event.moment)return 'say.moment';if(o.source.includes('soloLine'))return 'sim/talk solo';if(o.source.includes('/talk.js'))return 'sim/talk exchanges';if(o.source.includes('/ladder.js'))return 'sim/ladder';if(o.source.includes('/chat.js'))return 'sim/chat milestone';if(o.source.includes('/projects.js'))return 'sim/projects research';return 'sim/incentives';}if(b.source.includes('deskStandup'))return 'render desk standup';if(b.source.includes('updateStandup'))return 'render staged standup';return 'unknown';}
function yakSource(x,y){const s=new Map(x.origins).get(y.e.id)?.source??'';const file=[...s.matchAll(/src\/sim\/(\w+)\.js/g)].map(m=>m[1]).find(m=>!['chat','tick','registry'].includes(m));return `sim/${file??'chat'}`;}
for(const [kind,items,source,zeros] of [['Speech','bubbles',bubbleSource,['say.moment','sim/chat milestone','sim/projects research','sim/incentives']],['Yak','yak',yakSource,[]]]){
const counts=x=>{const c={};for(const l of x[items]){const k=source(x,l);c[k]=(c[k]??0)+.5;}return c;};const aa=before.map(counts),bb=after.map(counts);const keys=[...new Set([...zeros,...aa.flatMap(Object.keys),...bb.flatMap(Object.keys)])].sort();
out+=`\n<details><summary>${kind} rates by source</summary>\n\nEach cell is before / after per real-time minute. Zero means the source was absent or suppressed in that sample.\n\n| Source | ${before.map(x=>`${names[x.stage]} ${x.speed}x`).join(' | ')} |\n|---|${before.map(()=> '---:').join('|')}|\n`;for(const k of keys)out+=`| ${k} | ${before.map((_,i)=>pair(aa[i][k]??0,bb[i][k]??0)).join(' | ')} |\n`;out+='\n</details>\n';}
writeFileSync('shots/chatter/tables.md',out);
